CREATE TABLE attachment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id      BIGINT       NOT NULL REFERENCES bill (id) ON DELETE CASCADE,
    filename     VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size         BIGINT       NOT NULL,
    storage_key  VARCHAR(64)  NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX attachment_bill_id ON attachment (bill_id);
